import { checker } from 'vite-plugin-checker';
import { defineConfig } from 'vite';

import { fileURLToPath, URL } from 'url';
import fs from 'fs';

const pkg = require('./package.json');
const build = new Date().toISOString();

// Export vite config
export default defineConfig(async ({ mode }) => {
  /** @type {UserConfig} https://vitejs.dev/config/ */
  const config = {
    // https://vitejs.dev/config/#base
    base: './',
    // Resolver
    resolve: {
      // https://vitejs.dev/config/shared-options.html#resolve-alias
      alias: {
        '~bootstrap': fileURLToPath(
          new URL('./node_modules/bootstrap', import.meta.url)
        ),
        '~bootstrap-icons': fileURLToPath(
          new URL('./node_modules/bootstrap-icons', import.meta.url)
        ),
        '~dseg': fileURLToPath(new URL('./node_modules/dseg', import.meta.url)),
      },
    },
    // https://vitejs.dev/config/#server-options
    server: {
      fs: {
        // Allow serving files from one level up to the project root
        allow: ['..'],
      },
    },
    plugins: [
      // vite-plugin-checker
      // https://github.com/fi3ework/vite-plugin-checker
      checker({
        typescript: false,
        vueTsc: false,
        eslint: {
          lintCommand: `eslint ./src --fix --cache --cache-location ./node_modules/.vite/vite-plugin-eslint`, // for example, lint .ts & .tsx
        },
      }),
    ],
    // Build Options
    // https://vitejs.dev/config/#build-options
    build: {
      outDir: 'docs',
      // Minify option
      // https://vitejs.dev/config/#build-minify
      rollupOptions: {
        input: {
          index: fileURLToPath(new URL('./index.html', import.meta.url)),
          wml: fileURLToPath(new URL('./wml.html', import.meta.url)),
        },
      },
      target: 'esnext',
      minify: 'esbuild',
    },
    esbuild: {
      drop: mode === 'serve' ? [] : ['console'],
    },
  };

  fs.writeFileSync(
    fileURLToPath(new URL('./src/meta.js', import.meta.url)),
    `// This file is auto-generated by the build system.
const meta = {
  version: '${pkg.version}',
  date: '${build}',
};
export default meta;
`
  );

  return config;
});
