// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../closure-primitives/base.js', ['goog'], [], false);
goog.addDependency('../src/midi_event.js', ['Midi.Event'], ['Typedef'], false);
goog.addDependency('../src/mld.js', ['Mld.Parser'], ['Typedef'], false);
goog.addDependency('../src/player.js', ['SMF.Player'], ['Mld.Parser', 'SMF.Parser'], false);
goog.addDependency('../src/riff.js', ['Riff.Parser'], ['Typedef'], false);
goog.addDependency('../src/smf.js', ['SMF.Parser'], ['Midi.Event', 'Riff.Parser', 'Typedef'], false);
goog.addDependency('../src/typedef.js', ['Typedef'], [], false);
goog.addDependency('../src/worker.js', ['SMF.Worker'], ['Mld.Parser', 'SMF.Parser'], false);
